import { For, Show, createEffect, createSignal, onCleanup } from "solid-js";
import { Streamdown } from "./lib/streamdown";
import { parseHostMessage, type HostMessage } from "../shared/messages";
import { vscode } from "./utils/vscode";

const initial: Extract<HostMessage, { type: "state" }> = { type: "state", authenticated: false, osType: "MACOS", sessions: [], messages: [], recommendations: [], skillUpdates: [], updatesChecking: false, updatesInstalling: false, running: false, connection: "idle" };
const thinkingMessages = ["正在理解你的问题…", "正在分析相关上下文…", "正在检索相关信息…", "正在组织回答…"];
export default function App() {
  const [state, setState] = createSignal(initial); const [input, setInput] = createSignal(""); const [historyOpen, setHistoryOpen] = createSignal(false); const [locallySubmitted, setLocallySubmitted] = createSignal(false); const [thinkingIndex, setThinkingIndex] = createSignal(0); const [selectedUpdateKeys, setSelectedUpdateKeys] = createSignal<string[]>([]); let scroll!: HTMLDivElement; let followOutput = true; let lastSessionKey: string | undefined;
  const awaitingAssistantText = () => { const messages = state().messages; let lastUserIndex = -1; for (let index = messages.length - 1; index >= 0; index -= 1) { if (messages[index]?.role === "user") { lastUserIndex = index; break; } } return lastUserIndex >= 0 && !messages.slice(lastUserIndex + 1).some(message => message.role === "assistant" && message.content.trim().length > 0); };
  const showThinking = () => locallySubmitted() || (state().running && awaitingAssistantText());
  const receive = (event: MessageEvent<unknown>) => { const message = parseHostMessage(event.data); if (!message) return; if (message.type === "state") { if (message.currentSessionKey !== lastSessionKey) { followOutput = true; lastSessionKey = message.currentSessionKey; } setState(message); if (message.running || message.error) setLocallySubmitted(false); } else message.level === "error" ? console.error(message.message) : console.info(message.message); };
  const updateFollowOutput = () => { if (!scroll) return; followOutput = scroll.scrollHeight - scroll.scrollTop - scroll.clientHeight <= 48; };
  const thinkingTimer = window.setInterval(() => setThinkingIndex(index => (index + 1) % thinkingMessages.length), 1600);
  window.addEventListener("message", receive); onCleanup(() => { window.removeEventListener("message", receive); window.clearInterval(thinkingTimer); }); createEffect(() => { state().messages.length; state().messages.at(-1)?.content.length; showThinking(); thinkingIndex(); queueMicrotask(() => { if (followOutput && scroll) scroll.scrollTo({ top: scroll.scrollHeight, behavior: "smooth" }); }); });
  let updateSignature = "";
  createEffect(() => { const signature = state().skillUpdates.map(item => `${item.skillKey}:${item.localVersion}:${item.latestVersion}:${item.scopes.join(",")}`).join("|"); if (signature !== updateSignature) { updateSignature = signature; setSelectedUpdateKeys(state().skillUpdates.map(item => item.skillKey)); } });
  vscode.postMessage({ type: "ready" });
  const submitMessage = (content: string) => { const value = content.trim(); if (!value || state().running || locallySubmitted()) return; setLocallySubmitted(true); setThinkingIndex(0); vscode.postMessage({ type: "send-message", content: value }); setInput(""); };
  const send = () => submitMessage(input());
  return <main class="shell">
    <header class="topbar"><strong>研途助手</strong><div><button class="icon" title="历史会话" onClick={() => setHistoryOpen(!historyOpen())}>☰</button><Show when={state().authenticated}><button class="icon" title="新对话" onClick={() => vscode.postMessage({ type: "new-session" })}>＋</button></Show></div></header>
    <Show when={state().authenticated} fallback={<section class="login"><div class="logo">研</div><h2>连接研发助手平台</h2><p>使用飞书账号在浏览器中安全登录。扩展不会向对话页面暴露凭证。</p><Show when={state().loginPending && state().userCode} fallback={<button class="primary" onClick={() => vscode.postMessage({ type: "login" })}>登录研途助手</button>}><p class="device-label">请在浏览器核对设备码</p><div class="device-code" aria-label="设备码">{state().userCode}</div><p class="muted">正在等待授权…</p></Show><Show when={state().error}><p class="error">{state().error}</p></Show></section>}>
      <Show when={historyOpen()}><aside class="history"><div class="history-title">历史会话</div><For each={state().sessions}>{session => <div class={`session ${session.sessionKey === state().currentSessionKey ? "active" : ""}`}><button onClick={() => { vscode.postMessage({ type: "select-session", sessionKey: session.sessionKey }); setHistoryOpen(false); }}>{session.title}</button><button class="delete" title="删除" onClick={() => vscode.postMessage({ type: "delete-session", sessionKey: session.sessionKey })}>×</button></div>}</For><Show when={!state().sessions.length}><p class="muted">暂无历史对话</p></Show><button class="link" onClick={() => vscode.postMessage({ type: "logout" })}>退出登录</button></aside></Show>
      <div class="messages" ref={scroll} onScroll={updateFollowOutput}><Show when={!state().messages.length && !showThinking()}><section class="welcome"><h2>今天想解决什么问题？</h2><p>我会根据 CodeBuddy 和当前 {state().osType} 环境推荐合适的 Skill。</p><Show when={state().updatesChecking}><div class="update-checking" role="status">正在检查本地 Skill 更新…</div></Show><Show when={!state().updatesChecking && state().skillUpdates.length}><section class="skill-update-card"><div class="skill-update-card__head"><div><strong>发现可更新的 Skill</strong><small>平台已发布新版本，请选择要更新的项目</small></div><span class="skill-update-card__count">{state().skillUpdates.length}</span></div><div class="skill-update-list"><For each={state().skillUpdates}>{item => <label class="skill-update-row"><input type="checkbox" checked={selectedUpdateKeys().includes(item.skillKey)} onChange={event => setSelectedUpdateKeys(keys => event.currentTarget.checked ? [...new Set([...keys, item.skillKey])] : keys.filter(key => key !== item.skillKey))} /><span class="skill-update-copy"><strong>{item.name ?? item.skillKey}</strong><small>{item.localVersion} → {item.latestVersion}</small></span><span class="skill-update-scopes">{item.scopes.map(scope => <span class="scope-tag">{scope === "project" ? "项目" : "全局"}</span>)}</span></label>}</For></div><div class="skill-update-actions"><button class="link" onClick={() => vscode.postMessage({ type: "dismiss-updates" })}>稍后</button><button class="primary compact" disabled={!selectedUpdateKeys().length || state().updatesInstalling} onClick={() => vscode.postMessage({ type: "install-updates", skillKeys: selectedUpdateKeys() })}>{state().updatesInstalling ? "更新中…" : `更新所选（${selectedUpdateKeys().length}）`}</button></div></section></Show><Show when={!state().updatesChecking && state().updateError}><div class="update-error">{state().updateError}<button class="link" onClick={() => vscode.postMessage({ type: "retry-updates" })}>重试</button></div></Show><button class="welcome-skill-card" onClick={() => submitMessage("推荐研发全流程最佳实践的全部 Skill")}><span class="welcome-skill-card__count">36</span><span class="welcome-skill-card__copy"><strong>获取研发全流程 36 个 Skill</strong><small>覆盖需求、设计、编码、测试和交付阶段</small></span><span class="welcome-skill-card__arrow" aria-hidden="true">→</span></button></section></Show>
        <For each={state().messages}>{message => <article class={`message ${message.role}`}><div class="role">{message.role === "user" ? "你" : "研途助手"}</div><div class="content">{message.role === "assistant" ? <Streamdown mode={state().running ? "streaming" : "static"}>{message.content}</Streamdown> : message.content}</div></article>}</For>
        <Show when={showThinking()}><article class="message assistant thinking" role="status" aria-live="polite" aria-atomic="true"><div class="role">研途助手</div><div class="content"><Show keyed when={thinkingMessages[thinkingIndex()]}>{text => <span class="thinking-copy">{text}</span>}</Show><span class="thinking-dots" aria-hidden="true"><i></i><i></i><i></i></span></div></article></Show>
        <Show when={state().recommendations.length}><section class="recommendations"><h3>推荐 Skill</h3><For each={state().recommendations}>{skill => <article class="skill-card"><div class="skill-head"><strong>{skill.name ?? skill.skillKey}</strong><span class={`badge ${skill.status}`}>{label(skill.status)}</span></div><Show when={skill.version}><small>推荐版本 {skill.version}<Show when={skill.localVersion}> · 本地 {skill.localVersion}</Show></small></Show><p>{skill.reason ?? skill.description}</p><div class="actions"><Show when={skill.detailPath}><button onClick={() => vscode.postMessage({ type: "open-detail", detailPath: skill.detailPath! })}>详情</button></Show><Show when={skill.status === "missing" || skill.status === "update"}><button class="primary compact" onClick={() => state().currentRunKey && vscode.postMessage({ type: "install-skill", runKey: state().currentRunKey!, skillKey: skill.skillKey })}>安装</button></Show></div></article>}</For><Show when={state().recommendations.some(item => item.status === "missing" || item.status === "update")}><button class="primary install-all" onClick={() => state().currentRunKey && vscode.postMessage({ type: "install-all", runKey: state().currentRunKey! })}>安装全部缺失项</button></Show></section></Show>
        <Show when={state().error}><div class="error panel">{state().error}<button onClick={() => vscode.postMessage({ type: "refresh" })}>重试</button></div></Show>
      </div>
      <footer class="composer"><textarea value={input()} onInput={event => setInput(event.currentTarget.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey && !event.isComposing && event.keyCode !== 229) { event.preventDefault(); send(); } }} placeholder="向研途助手提问…" disabled={state().running}></textarea><Show when={state().running} fallback={<button class="send" disabled={!input().trim()} onClick={send}>发送</button>}><button class="send stop" onClick={() => vscode.postMessage({ type: "cancel-run" })}>停止</button></Show></footer>
    </Show>
  </main>;
}
function label(status: "project" | "global" | "update" | "missing"): string { return { project: "项目已安装", global: "全局已安装", update: "可更新", missing: "未安装" }[status]; }
